[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bridge = "APC3RWhf5mopwfBNufbdgMMCcZsJeT3pp7Se9BQ9VfGU"
token_wrapper = "K5syb9HJcd15UsBNfeqHhrUX9qL6H5e1PgKB157pW3M"
aggregator = "3JuUgDRh1tM91J9Dc1Dz57wiS54u4NFoWzegUaDBgs7Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
